{
 "title": "PC Metrics and Logs",
 "tags": [
  "node-exporter",
  "prometheus",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",instance=~\"$instance\"}[$__rate_interval])) * 100)",
     "legendFormat": "{{instance}} - CPU Usage"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=~\"$instance\"} / node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"$instance\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=~\"$instance\"} / node_memory_MemTotal_bytes{job=\"node-exporter\", instance=~\"$instance\"}))",
     "legendFormat": "{{instance}} - Mem Usage"
    }
   ]
  },
  {
   "title": "System Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"}"
    }
   ]
  }
 ]
}